### ISSUE TITLE
train.py 

### ISSUE THREAD

**Issue by zenglongjin** [TOJSSE-iData/PRODeepSyn#1]
I had an error as described in the documentation (https://www.5axxw.com/questions/content/8iqi0p) and were unable to resolve it. Thank you very much for your attention and consideration.

**Comment by TOJSSE-iData** [comment]
Could you please show more details about the error, including the error line and the tracebacks?

**Comment by TOJSSE-iData** [comment]
The large-sized file *.npy is stored in github using Git Large File Storage.
Please try `git lfs install && git lfs pull` for this.
See https://stackoverflow.com/a/67480110/7603207 for more details.

**Comment by zenglongjin** [comment]
Unfortunately, the git lfs pull command throws an error.  The error exhibits  'Could not pull
Errors logged to /home/shpc_1/PRODeepSyn/cell/.git/lfs/logs/20220510T080500.87691662.log
Use `git lfs logs last` to view the log.'  We are currently in 'python train.py target_ge.npy nodes_ge.npy --suffix sample'

**Comment by Ginufet** [comment]
@zenglongjin Sorry for the late reply. Could you please paste the detailed steps you perform when fetch the repo?
I've tried
`git clone git@github.com:TOJSSE-iData/PRODeepSyn.git`
`cd PRODeepSyn`
`git lfs install && git-lfs pull`
and successfully fetched the data.

**Comment by mahsayazdani** [comment]
I've had problems with pull from git-lfs too. Looks like it needs access. [Here](https://stackoverflow.com/questions/62905325/this-repository-is-over-its-data-quota-account-responsible-for-lfs-bandwidth-sh) I have found a solution.
